# SPDX-FileCopyrightText: 2025 E-Control Systems <info@econtrolsystems.com>
#
# SPDX-License-Identifier: GPL-3.0-only

services:
    package:
        build: 
            context: "."
            args:
              - "UID=${UID:-1000}"
              - "GID=${GID:-1000}"
        container_name: ptouch_print_packaging
        volumes:
            - .:/app
        command: "bash ./package.sh"
        working_dir: /app
