
env:
  OUTDIR: 'out'

on:
  push:
    tags:
      - '*'

jobs:
  build-and-package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]

    container:
      image: debian:trixie-slim

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          echo 'DEBIAN_FRONTEND=noninteractive' >> /etc/environment
          apt update && apt install -y checkinstall libusb-1.0-0-dev libgd-dev git cmake make gcc gettext printer-driver-ptouch sudo
          mkdir -p /etc/udev/rules.d

      - name: Build and Package
        run: bash ./package.sh

      - name: Organize Artifacts
        run: |
          mkdir -p ${OUTDIR}
          cp *.tar.gz ${OUTDIR}/
          cp *.deb ${OUTDIR}/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs-${{ matrix.os }}
          path: ${{ env.OUTDIR }}/

  release:
    needs: build-and-package
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -l --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: build-outputs-*
          path: ${{ env.OUTDIR }}/
          merge-multiple: true

      - name: Generate Checksum
        run: | 
          cd ${OUTDIR}
          find * -type f -exec sha256sum {} >> sha256sums.txt \;

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith('${{ github.ref }}', 'refs/tags/')
        with:
          files: |
            out/*
            CHANGELOG.md
          name: Release ${{ github.ref_name }}
          body: ${{ steps.git-cliff.outputs.content }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
